name: Build and Deploy Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm-chart/**'
      - '.github/workflows/**'
      - '**Dockerfile'
      - '**/*.py'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      image-tag: \${{ steps.set-image-tag.outputs.image-tag }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set image tag
      id: set-image-tag
      run: echo "image-tag=youssef:latest" >> \$GITHUB_OUTPUT

    - name: Docker Hub Login
      uses: docker/login-action@v2.2.0
      with:
       registry: docker.io
       username: ${{ secrets.USER_NAME }}
       password: ${{ secrets.USER_PASS }}

    - name: Build and push Docker image
      id: build-push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: youssefnasser537/youssef:${{ github.sha }}
        cache-from: type=registry,ref=${{ vars.USER_NAME }}/youssef:latest
        cache-to: type=inline
        


    - name: verify image exists
      run: |
        if ! docker pull youssefnasser537/youssef:latest; then
        echo "Warning: Image not found in Docker Hub, but continuing deployment"
        echo "This is normal if you're using a private registry or different tag"
        fi

  deploy-helm-chart:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
         echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
         chmod 600 kubeconfig
         export KUBECONFIG=$(pwd)/kubeconfig
         kubectl cluster-info
         kubectl get nodes

    - name: Deploy Helm chart
      run: |
        helm uninstall youssef-v1 --kubeconfig kubeconfig || true
        helm upgrade --install youssef-v1 helm-chart \
        --set image.repository=youssefnasser537/youssef \
        --set image.tag=${{ github.sha }} \
        --namespace youssef \
        --create-namespace \
        --kubeconfig kubeconfig \

    
    - name: Debug Deployment Issues
      run: |
        echo "### Pod Details ###"
        kubectl get pods -l place=iti,name=youssef --namespace youssef --kubeconfig kubeconfig -o wide
        
        echo "## Pod Events ##"
        kubectl describe pods -l place=iti,name=youssef --namespace youssef --kubeconfig kubeconfig
        
        echo "## Deployment Events ##"
        kubectl describe deployment youssef-v1-deployment --namespace youssef --kubeconfig kubeconfig

    - name: Verify Deployment
      run: |
       echo "### Checking Rollout Status ###"
       kubectl rollout status deployment/youssef-v1-deployment --namespace youssef --kubeconfig kubeconfig || true
    
       echo "### Checking Pods ###"
       kubectl get pods -l place=iti,name=bashar -o wide --namespace youssef --kubeconfig kubeconfig 
      
       echo "### pods logs ###"
        kubectl logs -l place=iti,name=youssef --namespace youssef --kubeconfig kubeconfig || echo "No logs available yet"

       echo "### Checking Services ###"
       kubectl get svc -l place=iti,name=youssef --namespace youssef --kubeconfig kubeconfig

       echo "### Helm Resources ###"
       helm get manifest youssef-v1 --namespace youssef --kubeconfig kubeconfig
    
       echo "### Helm Status ###"
       helm status youssef-v1 --namespace youssef --kubeconfig kubeconfig
